### ISSUE TITLE
Easter Egg - thing

### ISSUE THREAD

**Issue by UltraBlackLinux** [Alcatraz323/audiohq_md2#1]
Please make the easter egg easier accessible.
From the code, I guess I need to get a specific picture in the and 10 easter egg, but it takes soo long to solve them - please.
Thanks!

**Comment by Alcatraz323** [comment]
Seems like your guess is wrong, the quiz answer is encrypted using md5, so you are not seeing the true answer, Also, this is a two section easter egg. You need to input some morsecode somewhere to unlock the true quiz

**Comment by UltraBlackLinux** [comment]
@Alcatraz323 I mean I guess my first thought was bruh - I now understand the longclick thing. I got one problem though (I hope I am right) I can't input the morsecode on the easter egg button if that is where I should do that, it doesn't work :|

**Comment by Alcatraz323** [comment]
The place for Morse is in About(Activity), the Version list Item. If you
still can't input, you may try change the
Constant.DEFAULT_VALUE_PREF_SHOW_THEME_SETTINGS to true to force unlock it.

在 2020年11月28日星期六，UltraBlackLinux <notifications@github.com> 写道：

**Comment by UltraBlackLinux** [comment]
@Alcatraz323 
So I guess you mean the button, that sais "Android-Version \n 10" It doesn't work. Everytime I longpress I opens a "copy" popup, and I have to click anywhere to close it, so that seems not right.
Also adding that line to the shared prefs (`<boolean name="DEFAULT_VALUE_PREF_SHOW_THEME_SETTINGS" value="true" />`) didn't do anything... Pretty weird...
Please provide an exact walkthrough of the easteregg - so difficult bruh....

**Comment by Alcatraz323** [comment]
For the Easter egg you need 1126 or later version installed, then go to
"About", short click and long click the version list item as .----...-,
then go "Settings -> Others -> What's this". There are two quiz, one math
which answer is "An*2ive*sar*2y" and a Sudoku I forgot the answer, after
this you can unlock the content in "Settings->Other"

在 2020年12月12日星期六，UltraBlackLinux <notifications@github.com> 写道：

**Comment by UltraBlackLinux** [comment]
@Alcatraz323 Sheeeesh
The thing with the easter-egg entry hint was so damn misleading. I thought you meant the android one - silly me...
Thanks anyways for the now working stuff, I like it :)
